const GET_TOOLS_BY_NAME = "GET_TOOLS_BY_NAME";
const GET_TOOLS = "GET_TOOLS";
const GET_TOOLS_BY_ID = "GET_TOOLS_BY_ID";
const CREATE_USER = "CREATE_USER";
const ADD_TO_CART = "ADD_TO_CART";
const REMOVE_FROM_CART = "REMOVE_FROM_CART";
const ERROR_404 = 'ERROR_404'
const ORDER_BY_NAME = "ORDER_BY_NAME";
const ORDER_BY_PRICE = "ORDER_BY_PRICE";
const SET_CURRRENT_PAGE = "SET_CURRENT_PAGE";
const CLEAN_BDD = "CLEAN_BDD"

export {
  GET_TOOLS_BY_NAME,
  GET_TOOLS,
  GET_TOOLS_BY_ID,
  CREATE_USER,
  ADD_TO_CART,
  REMOVE_FROM_CART,
  ERROR_404,
  ORDER_BY_NAME,
  ORDER_BY_PRICE,
  SET_CURRRENT_PAGE,
  CLEAN_BDD
};
