const GET_TOOLS_BY_NAME = "GET_TOOLS_BY_NAME";
const GET_TOOLS = "GET_TOOLS";
const GET_TOOLS_BY_ID = "GET_TOOLS_BY_ID";
const CREATE_USER = "CREATE_USER";
const ADD_TO_CART = "ADD_TO_CART";
const REMOVE_FROM_CART = "REMOVE_FROM_CART";

export {
  GET_TOOLS_BY_NAME,
  GET_TOOLS,
  GET_TOOLS_BY_ID,
  CREATE_USER,
  ADD_TO_CART,
  REMOVE_FROM_CART,
};
